In [2]:
import pandas as pd
users_ratings=pd.read_csv("test_set_all.csv")
users_pop=pd.read_csv("test_set_pop_only.csv")

In [4]:
users=set(users_ratings['userId'].values)

In [12]:
len(users)

['userId', 'movieId', 'rating']

In [41]:
data =pd.DataFrame(columns=['userId','movieIds'])
for user in users:
    movies = users_ratings[users_ratings.userId == user]
    movies = movies.filter(items=['movieId'])
    movies_set = set(movies['movieId'].values)
    
    moviestr = ','.join(str(s) for s in movies_set)
    moviestr
    row = [str(user) , moviestr]
    data.loc[len(data)] = row

In [43]:
data.to_csv('exclude_list.tsv',sep='\t',index=False,header=False)

In [4]:
user_recs_all=pd.read_csv('Recommendations/recspop.tsv',sep="\t")
user_recs_pop=pd.read_csv('Recommendations/recsfull.tsv',sep="\t")

In [59]:
movie_data = pd.read_csv('Recommendations/all_movies_count.tsv',sep="\t")

In [60]:
movie_data

     MovieId  Count
0     122882      2
1          6      1
2     122886      4
3     109576     75
4      88075      4
5       1035      1
6     122892      1
7     107535      3
8         16      1
9      76816     18
10      2067      1
11        19      2
12     60436      8
13      3095      1
14    122904      2
15     30747      3
16      2076      1
17        28      1
18    140319     26
19        29      1
20        34      1
21      1059      2
22    119844     65
23      1061      1
24    122920      4
25      3114      1
26    164905      1
27    102445      1
28    151597      5
29      4148      1
..       ...    ...
480     1982      1
481     4034      1
482   180161     13
483     8132      1
484     5060      1
485      968      4
486    98251      6
487     5067      6
488     1997      2
489   118734      3
490   107477     24
491   115669     15
492     2011      2
493     2012      1
494    91104      2
495     2018      1
496     2019      3
497     7140      1
498     2021      2
499   144356     27
500     2023      2
501     2025      1
502    77802      1
503   179183      1
504   179181      2
505     7153     20
506   153584      6
507    86002      2
508   106489      1
509   162808    186

[510 rows x 2 columns]

movie_data

In [61]:
movie_data =movie_data.drop(movie_data.columns[movie_data.columns.str.contains('unnamed',case = False)],axis = 1)

In [62]:
movie_data=movie_data.sort_values(by='Count',ascending=False)

In [66]:
movie_data

     MovieId  Count
392   178951    862
394   178955    862
391   178947    857
400   178957    855
399   178959    854
334   104085    849
393   178949    848
346   105144    842
288    97817    823
298    26153    779
125   123091    747
414   139048    618
42    131140    615
39     32836    569
361   133837    530
212     1360    492
193   103741    419
266   106970    406
395   118536    324
118   149711    319
348   139966    318
110   149700    315
182   154917    306
421   119615    284
172   129309    265
119     2254    260
362   139986    256
407   138010    250
426   146252    232
405   160533    195
..       ...    ...
324    31362      1
310      593      1
311      595      1
313      608      1
175    45342      1
315   106082      1
316    31333      1
317     2662      1
171     3355      1
319     1639      1
320     2671      1
321     2672      1
170     1307      1
323    86644      1
169    64793      1
157    60684      1
327    27276      1
328     1676      1
165     2324      1
163     4370      1
331    93840      1
332     2706      1
333     2707      1
162     1298      1
335     2710      1
161      273      1
159     2318      1
339     3746      1
158     7438      1
255     2478      1

[510 rows x 2 columns]

In [78]:
pop_movie=movie_data.query('Count>40')

In [82]:
pop_movie.columns=['movieId','Count']

In [83]:
pop_movieIds=set(pop_movie['movieId'])

In [84]:
import numpy as np

In [85]:
pop_movieIds

{1360,
 2254,
 3226,
 8402,
 26153,
 32836,
 73868,
 97817,
 103741,
 104085,
 105144,
 106970,
 109576,
 118536,
 119615,
 119844,
 123091,
 129309,
 130332,
 131140,
 133837,
 134433,
 135055,
 135388,
 138010,
 139048,
 139966,
 139974,
 139986,
 140000,
 143515,
 146252,
 147839,
 149586,
 149700,
 149711,
 149790,
 151989,
 154917,
 159259,
 160533,
 161936,
 162808,
 173299,
 177209,
 178947,
 178949,
 178951,
 178955,
 178957,
 178959}

In [162]:
for index,row in user_recs_all.iterrows():
    movie_string=row["Movies"].split(",")
    movie_string=map(int,movie_string)
    movie_set=set(movie_string)
    count=0
    for x in movie_set:
        if x in pop_movieIds:
            count += 1
    print count
    user_recs_all.loc[[index],["popCount"]]=count
    user_recs_all.loc[[index],["unpopCount"]]=20-count

1
0
0
0
0
0
0
0
0
0
0
3
0
0
0
0
2
0
0
0
3
0
0
10
3
0
0
0
1
0
0
0
0
0
0
2
18
0
1
0
0
0
0
0
0
0
18
0
1
4
0
2
0
4
0
0
0
0
0
3
0
0
0
0
0
0
0
0
0
0
0
0
0
4
0
6
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
2
0
0
3
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
2
0
0
0
0
1
0
0
0
0
0
0
0
5
0
0
0
3
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
3
0
0
0
0
0
0
0
7
0
17
0
0
2
0
0
0
0
15
0
0
0
0
0
0
0
0
0
0
0
0
0
5
0
0
0
0
0
0
0
1
0
0
16
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
2
10
0
0
0
0
0
0
0
0
0
0
0
0
0
3
0
0
2
6
2
0
0
0
0
0
0
0
0
0
0
0
0
0
0
3
0
0
0
0
0
0
0
0
19
0
0
0
0
0
0
0
2
0
0
0
4
19
0
0
0
0
0
4
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
6
0
0
0
0
0
0
0
0
0
0
0
11
0
0
0
0
0
0
0
7
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
2
0
1
1
0
0
0
0
0
15
0
9
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
7
0
0
0
0
0
3
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
5
0
0
0
0
0
0
0
0
0
0
0
3
0
0
0
0
0
0
0
0
0
0
0
0
5
0
0
0
0
0
0
0
0
0
0
0
18
0
0
20
0
0
9
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
6
0
0
0
0
0
1
2
0
0
0
6
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
3
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
7
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
2
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
2
0
0
0
0
1
15
0
0
0
0
0
0
0
0
0
0
0
0
0
11
0
0
0
20
0
3
0
0
0
0
1
7
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
3
1
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
14
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
12
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
13
0
0
0
0
0
0
0
0
0
0
0
0
0
4
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
10
0
4
3
20
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
20

In [163]:
user_recs

,userId,Movies,popCount,unpopCount
0,21783,"103741,1360,858,26153,135055,3226,149586,8402,...",1,19
1,42265,"104085,178951,178949,178957,178955,178959,1789...",0,20
2,42287,"104085,105144,178951,178949,178957,178955,1789...",0,20
3,42298,"104085,178951,178949,178957,178955,178959,1789...",0,20
4,42969,"105144,104085,106970,178951,178949,178957,1789...",0,20
5,43191,"105144,178951,178949,178957,178955,178959,1789...",0,20
6,43236,"26153,103741,105144,104085,1360,97817,135055,1...",0,20
7,43277,"103741,105144,178951,178949,178957,178955,1789...",0,20
8,43717,"26153,104085,105144,1360,103741,97817,178951,1...",0,20
9,44240,"104085,178951,178949,178957,178955,178959,1789...",0,20
10,44365,"103741,106970,123091,162808,1360,180045,173299...",0,20
11,44655,"7153,4993,5952,1360,26153,73868,104085,160159,...",3,17
12,46351,"104085,105144,26153,178955,178951,178959,17894...",0,20
13,46439,"104085,105144,178951,178949,178957,178955,1789...",0,20
14,46702,"105144,103741,104085,154917,106970,123091,2615...",0,20
15,47183,"103741,123091,26153,32836,178951,178949,178957...",0,20
16,47664,"858,1221,106970,162808,154917,32836,146252,131...",2,18
17,47775,"104085,26153,1360,138010,73868,146252,3226,105...",0,20
18,48053,"104085,105144,178951,178949,178957,178955,1789...",0,20
19,48418,"104085,178951,178949,178957,178955,178959,1789...",0,20
20,49754,"86347,720,86377,178951,178949,178957,178955,17...",3,17
21,50312,"104085,178951,178949,178955,178957,178959,1789...",0,20
22,50626,"104085,105144,178955,178951,178959,178949,1789...",0,20
23,50738,"745,1221,1148,1223,1287,720,7502,912,103741,14...",10,10
24,51718,"7153,4993,5952,104085,26153,1360,105144,8402,1...",3,17
25,51796,"103741,104085,26153,105144,1360,178951,178949,...",0,20
26,52146,"105144,178951,178949,178957,178955,178959,1789...",0,20
27,52423,"103741,123091,106970,26153,105144,178951,17894...",0,20
28,52950,"104085,97817,178951,178949,178957,178955,17895...",1,19
29,52962,"104085,178951,178949,178957,97817,178955,17895...",0,20
...,...,...,...,...
969,308724,"131140,105144,139048,123091,178951,178949,1789...",0,20
970,309019,"103741,26153,1360,106970,162808,135055,32836,1...",0,20
971,309326,"3608,1405,2459,1261,968,3868,1974,105144,11218...",10,10
972,309588,"105144,104085,178951,178949,178957,178955,1789...",0,20
973,309671,"6934,104085,6365,105144,133837,178951,178949,1...",4,16
974,310008,"7502,86504,527,2920,103741,106970,44555,26153,...",3,17
975,310036,"1483,2427,1094,3176,2712,4370,203,2672,71135,1...",20,0
976,310054,"104085,178951,178949,178957,178955,178959,1789...",0,20
977,310276,"123091,105144,106970,104085,154917,131140,1390...",0,20
978,310500,"104085,1360,26153,178951,178957,178949,178955,...",0,20
979,310738,"105144,104085,178951,178949,178957,178955,1789...",0,20
980,310863,"104085,105144,178951,178949,178957,178955,1789...",0,20
981,310879,"104085,123091,97817,105144,178951,178949,17895...",0,20
982,311090,"104085,178951,178949,178957,178955,178959,1789...",0,20
983,311422,"104085,105144,178951,178949,178957,178955,1789...",0,20
984,311513,"105144,104085,178951,178949,178957,178955,1789...",0,20
985,311662,"104085,133837,178951,178949,178955,178957,1789...",0,20
986,311716,"105144,104085,178951,178949,178957,178955,1789...",0,20
987,312272,"105144,104085,131140,139048,178951,178949,1789...",0,20
988,312491,"104085,105144,178951,178949,178957,178955,1789...",0,20
989,313268,"104085,133837,178951,178957,178949,178955,1789...",0,20
990,313608,"105144,178951,178949,178957,178955,178959,1789...",0,20
991,314805,"104085,105144,178951,178949,178957,178955,1789...",0,20
992,315052,"104085,178951,178949,178957,178955,178959,1789...",0,20
993,316024,"104085,133837,2254,178959,178947,178957,178955...",1,19
994,316459,"104085,105144,178951,178949,178957,178955,1789...",0,20
995,317270,"104085,105144,97817,131140,149711,139048,14970...",0,20
996,317698,"105144,106970,123091,178951,178949,178957,1789...",0,20
997,317734,"105144,106970,104085,32836,103741,162808,15491...",0,20
998,317833,"2023,7502,524,1221,2231,1093,2707,858,3809,6,2...",20,0

In [164]:
user_recs=user_recs.filter(items= ['userId','popCount','unpopCount'])

In [165]:
user_recs.to_csv('poponly_pop_unpop_count.csv',index=False,header=True,sep=',')